language: python
python:
  - 3.7
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
addons:
  apt:
    packages:
      - lammps

install:
  - pip install .

script:
  - lammps -in lammps/in.melt
  - python script/calc_scattering.py
  - python script/export_first_frame.py xpcs00512.h5 xpcs00512-frame0.png
  - tar czf xpcs-baseline.tar.gz xpcs00512.h5 xpcs00512-frame0.png

deploy:
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    skip_cleanup: true
    file_glob: true
    file: xpcs-baseline.tar.gz
    on:
      tags: true
